project:
  type: book
  output-dir: _book
  preview: 
    port: 4201
    browser: true

book:
  title: "Menjadi Data Analyst"
  subtitle: "Menguasai Statistika, Spreadsheet, SQL, Programming, dan Visualisasi untuk Pemula"
  author: 
    # - name: Dr. Bagus Sartono, M.Si
    - name: Aep Hidayatuloh #, S.Stat
      # affiliations: StarCore Analytics
      email: aephidayatuloh.mail@gmail.com
  date: today
  date-format: D MMM YYYY
  cover-image: book-cover-rabbit-front.png #dark-cover.png
  favicon: icon.png
  sidebar:
    collapse-level: 1
  chapters:
    - part: DAFTAR ISI
    - index.qmd
    
    - part: dasar.qmd
      chapters: 
        - polapikir.qmd
        - fondasi.qmd 
        - text: "Keuntungan Data Analyst"
          file: keuntungan.qmd 
        - text: "Metrik dalam Bisnis"
          file: metric.qmd 
    
    - part: st-statistik.qmd
      chapters: 
        - st-tipedata.qmd
        - st-dasarstats.qmd
        - st-eksplorasi.qmd
        - st-sebaran.qmd
        - st-ujihipotesis.qmd 
        - text: "Analisis Korelasi" 
          file: st-korelasi.qmd
        
    - part: ss-spreadsheet.qmd
      chapters: 
        - ss-pengenalan.qmd
        - ss-dataprep.qmd
        - ss-formula-fungsi.qmd 
        - ss-analisis-stat.qmd 
        - ss-viz.qmd 
        - ss-lain-lain.qmd 
        - ss-tabelformula.qmd
        - ss-pivot.qmd
        - ss-chart.qmd
    
    - part: sql-sql.qmd
      chapters: 
        - sql-database.qmd
        - sql-select.qmd  # SELECT Clause
        - sql-filter.qmd  # Filter WHERE
        - sql-order.qmd   # Sort 
        - sql-summary.qmd # Membuat variabel dari 
        - sql-join.qmd
    
    - part: programming.qmd
      chapters: 
        - text: "Dasar R Programming" 
          file: r-programming.qmd 
        - text: "Alur Kendali" 
          file: r-ifloop.qmd 
        - text: "Memperoleh Data" 
          file: r-importexport.qmd
        - text: "Eksplorasi Data" 
          file: r-eksplor.qmd
    
    - part: komunikasi.qmd 
      chapters: 
        - visualisasi.qmd
        - storytelling.qmd
    
    - part: pr-proyek.qmd 
      chapters: 
        - usecase1.qmd
        - usecase2.qmd

    - part: tips.qmd 
      chapters: 
        - portofolio.qmd
        - jobseek.qmd

    - pustaka.qmd
    - penulis.qmd
    - penutup.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: tibble
    css: style.css
    code-link: true 
    toc-depth: 3 
    toc-expand: false
    section-divs: false
  docx:
    reference-doc: custom-reference-doc.docx
    toc: true
    toc-depth: 2
    number-sections: false
    highlight-style: github
  # pdf:
  #   documentclass: scrbook

knitr: 
  opts_chunk: 
    comment: "#>" 

